apiVersion: v1
kind: Service
metadata:
  name: streamlit-moatless-service
spec:
  selector:
    app: streamlit-moatless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer